// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqc7BsCDbc06A8cWDsPPD71b1PdHS42d0',
    appId: '1:200209219735:web:010bf2e296df7dbbd2a9d2',
    messagingSenderId: '200209219735',
    projectId: 'dagensord-58b7a',
    authDomain: 'dagensord-58b7a.firebaseapp.com',
    storageBucket: 'dagensord-58b7a.appspot.com',
    measurementId: 'G-TSNVTFE47N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsCEdkRNvatRbyEm4a1uIoONna16VVsII',
    appId: '1:200209219735:android:c3ba64acaf480e90d2a9d2',
    messagingSenderId: '200209219735',
    projectId: 'dagensord-58b7a',
    storageBucket: 'dagensord-58b7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhP5ilFWXrtPUbxPyUVxOxd0BfJAM7IKg',
    appId: '1:200209219735:ios:d1afbd001d02cc0fd2a9d2',
    messagingSenderId: '200209219735',
    projectId: 'dagensord-58b7a',
    storageBucket: 'dagensord-58b7a.appspot.com',
    iosBundleId: 'com.example.dagensord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhP5ilFWXrtPUbxPyUVxOxd0BfJAM7IKg',
    appId: '1:200209219735:ios:5482d798932bf10dd2a9d2',
    messagingSenderId: '200209219735',
    projectId: 'dagensord-58b7a',
    storageBucket: 'dagensord-58b7a.appspot.com',
    iosBundleId: 'com.example.dagensord.RunnerTests',
  );
}
